name: Monthly Meeting Reminder

on:
  schedule:
    - cron: '0 0 23 * *' # Run on the 23rd of every month at 00:00 UTC
  workflow_dispatch:
jobs:

  create-issue:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Get next meeting date
      id: next-meeting
      run: |
        next_month=$(date -d 'next month' +'%Y-%m-01')
        day=$(date -d "$next_month +$(date -d "$next_month" +'%u' | awk '{print 3-$1%7"%7"}') day" +'%Y-%m-%d')
        echo "::set-output name=date::$day"
        
    - name: Create monthly meeting issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Meeting [${{ steps.next-meeting.outputs.date }}]
        content-filepath: .github/ISSUE_TEMPLATE/meeting.md
        labels: meeting
